### PR TITLE
I Will

### PR DESCRIPTION
**Pull request by benhamill**
A blog post about how I now work for Under Armour.

### CODE REVIEW

**Comment by h3h** [comment]
Needs real apostrophes.

“I’d’ve” is a great construction. I’ve never seen that before.

:+1:

**Comment by benhamill** [comment]
The rendering engine will make the apostrophes real. "I'd've" is real good. It's no "y'all'd've", but it's close.

**Comment by benhamill** [comment]
And thanks.

**Comment by kristjan** [comment]
Now I'll be looking for an excuse to use "y'all'd've". I'd also promote "whichse" for when you need "whose" on something inanimate.

**Pull request merged**
